from .runners import Remote as Remote, RemoteShell as RemoteShell
from .util import debug as debug, get_local_user as get_local_user
from invoke.config import Config as InvokeConfig

class Config(InvokeConfig):
    prefix: str
    @classmethod
    def from_v1(cls, env, **kwargs): ...
    def __init__(self, *args, **kwargs) -> None: ...
    def set_runtime_ssh_path(self, path) -> None: ...
    def load_ssh_config(self) -> None: ...
    def clone(self, *args, **kwargs): ...
    @staticmethod
    def global_defaults(): ...
