from invoke.config import Config as InvokeConfig

from .runners import Remote as Remote
from .runners import RemoteShell as RemoteShell
from .util import debug as debug
from .util import get_local_user as get_local_user

class Config(InvokeConfig):
    prefix: str
    @classmethod
    def from_v1(cls, env, **kwargs): ...
    def __init__(self, *args, **kwargs) -> None: ...
    def set_runtime_ssh_path(self, path) -> None: ...
    def load_ssh_config(self) -> None: ...
    def clone(self, *args, **kwargs): ...
    @staticmethod
    def global_defaults(): ...
