from collections.abc import Generator
from typing import Literal, overload

from _typeshed import Incomplete
from invoke.context import Context
from invoke.runners import Result

from .config import Config as Config
from .exceptions import InvalidV1Env as InvalidV1Env
from .transfer import Transfer as Transfer
from .tunnels import Tunnel as Tunnel
from .tunnels import TunnelManager as TunnelManager

def opens(method, self, *args, **kwargs): ...
def derive_shorthand(host_string): ...

class Connection(Context):
    host: Incomplete
    original_host: Incomplete
    user: Incomplete
    port: Incomplete
    ssh_config: Incomplete
    gateway: Incomplete
    forward_agent: Incomplete
    connect_timeout: Incomplete
    connect_kwargs: Incomplete
    client: Incomplete
    transport: Incomplete
    @classmethod
    def from_v1(cls, env, **kwargs): ...
    inline_ssh_env: Incomplete
    def __init__(
        self,
        host,
        user: Incomplete | None = None,
        port: Incomplete | None = None,
        config: Incomplete | None = None,
        gateway: Incomplete | None = None,
        forward_agent: Incomplete | None = None,
        connect_timeout: Incomplete | None = None,
        connect_kwargs: Incomplete | None = None,
        inline_ssh_env: Incomplete | None = None,
    ) -> None: ...
    def resolve_connect_kwargs(self, connect_kwargs): ...
    def get_gateway(self): ...
    def __eq__(self, other): ...
    def __lt__(self, other): ...
    def __hash__(self): ...
    def derive_shorthand(self, host_string): ...
    @property
    def is_connected(self) -> bool: ...
    def open(self): ...
    def open_gateway(self): ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc) -> None: ...
    def create_session(self): ...
    @overload
    def run(self, command: str, disown: Literal[True], **kwargs) -> None: ...
    @overload
    def run(self, command: str, **kwargs) -> Result: ...
    def sudo(self, command: str, **kwargs): ...
    def shell(self, **kwargs): ...
    def local(self, *args, **kwargs): ...
    def sftp(self): ...
    def get(self, *args, **kwargs): ...
    def put(self, *args, **kwargs): ...
    def forward_local(
        self,
        local_port,
        remote_port: Incomplete | None = None,
        remote_host: str = "localhost",
        local_host: str = "localhost",
    ) -> Generator[None]: ...
    def forward_remote(
        self,
        remote_port,
        local_port: Incomplete | None = None,
        remote_host: str = "127.0.0.1",
        local_host: str = "localhost",
    ) -> Generator[None]: ...
