import invoke

from .exceptions import NothingToDo as NothingToDo
from .tasks import ConnectionCall as ConnectionCall
from .util import debug as debug

class Executor(invoke.Executor):
    def normalize_hosts(self, hosts): ...
    def expand_calls(self, calls, apply_hosts: bool = True): ...
    def parameterize(self, call, connection_init_kwargs): ...
    def dedupe(self, tasks): ...
