from .connection import Connection as Connection
from .exceptions import GroupException as GroupException

class Group(list):
    def __init__(self, *hosts, **kwargs) -> None: ...
    @classmethod
    def from_connections(cls, connections): ...
    def run(self, *args, **kwargs): ...
    def sudo(self, *args, **kwargs): ...
    def put(self, *args, **kwargs): ...
    def get(self, *args, **kwargs): ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc) -> None: ...

class SerialGroup(Group): ...

def thread_worker(cxn, queue, method, args, kwargs) -> None: ...

class ThreadingGroup(Group): ...

class GroupResult(dict):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def succeeded(self): ...
    @property
    def failed(self): ...
