from . import Config as Config, Executor as Executor
from _typeshed import Incomplete
from invoke import Program

class Fab(Program):
    def print_version(self) -> None: ...
    def core_args(self): ...
    collection: Incomplete
    def load_collection(self) -> None: ...
    def no_tasks_given(self) -> None: ...
    config: Incomplete
    def create_config(self) -> None: ...
    def update_config(self) -> None: ...
    def parse_core(self, *args, **kwargs) -> None: ...

def make_program(): ...

program: Incomplete
