from _typeshed import Incomplete
from invoke import Result as InvokeResult, Runner

def cares_about_SIGWINCH(): ...

class Remote(Runner):
    inline_env: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    channel: Incomplete
    def start(self, command, shell, env, timeout: Incomplete | None = None) -> None: ...
    def send_start_message(self, command) -> None: ...
    def run(self, command, **kwargs): ...
    def read_proc_stdout(self, num_bytes): ...
    def read_proc_stderr(self, num_bytes): ...
    def close_proc_stdin(self): ...
    @property
    def process_is_finished(self): ...
    def send_interrupt(self, interrupt) -> None: ...
    def returncode(self): ...
    def generate_result(self, **kwargs): ...
    def stop(self) -> None: ...
    def kill(self) -> None: ...
    def handle_window_change(self, signum, frame) -> None: ...

class RemoteShell(Remote):
    def send_start_message(self, command) -> None: ...

class Result(InvokeResult):
    connection: Incomplete
    def __init__(self, **kwargs) -> None: ...
