[tox]
envlist = py314

[testenv]

[testenv:test]
runner = uv-venv-lock-runner
description = run tests
commands =
    pytest --cov=sarc --cov-branch --cov-report= --doctest-modules --durations=50 --durations-min 1 -vv --timeout=20 -vvv tests/ {posargs}
    coverage report -m

[testenv:test_dev]
runner = uv-venv-lock-runner
description = run tests (dev)
commands =
    pytest --cov=sarc --cov-branch --cov-report= --doctest-modules --durations=50 --durations-min 1 -vv --timeout=20 -vvv {posargs}
    coverage report -m

[testenv:ruff]
runner = uv-venv-lock-runner
description = run code checks
commands =
    ruff format --check
    ruff check --no-fix

[testenv:mypy]
runner = uv-venv-lock-runner
description = run mypy
commands =
    mypy sarc
