receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
      
processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  file/logs:
    path: /files/logs.json
  file/traces:
    path: /files/traces.json

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, files/logs]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, files/traces]
