from sarc.users.acquire import filter_duplicate_drac_members


def test_filter_duplicate_drac_members():
    # Test data
    LD_drac_members = [
        # user1: a user with 2 different activation status, the activated one should be kept (the first one in this case)
        {
            "rapi": "therapi",
            "groupname": "thegroup",
            "name": "User One",
            "position": "Chercheur",
            "institution": "random uni",
            "department": "patate",
            "sponsor": "John Doe",
            "permission": "Member",
            "activation_status": "activated",
            "username": "user1",
            "ccri": "dunno",
            "email": "user1@mail.ca",
            "member_since": "2020-05-01 15:47:52 -0400",
        },
        {
            "rapi": "therapi",
            "groupname": "thegroup",
            "name": "User One",
            "position": "Étudiant à la maîtrise",
            "institution": "random uni",
            "department": "patate",
            "sponsor": "John Doe",
            "permission": "Member",
            "activation_status": "older_deactivated",
            "username": "user1",
            "ccri": "dunno",
            "email": "user1@mail.ca",
            "member_since": "2017-04-27 17:12:50 -0400",
        },
        # user2: a simple user with one activated entry
        {
            "rapi": "therapi",
            "groupname": "thegroup",
            "name": "User Two",
            "position": "Chercheur",
            "institution": "random uni",
            "department": "patate",
            "sponsor": "John Doe",
            "permission": "Member",
            "activation_status": "activated",
            "username": "user2",
            "ccri": "dunno",
            "email": "user2@mail.ca",
            "member_since": "2020-05-01 15:47:52 -0400",
        },
        # user3: a simple user with one deactivated entry
        {
            "rapi": "therapi",
            "groupname": "thegroup",
            "name": "User The Third",
            "position": "Chercheur",
            "institution": "random uni",
            "department": "patate",
            "sponsor": "John Doe",
            "permission": "Member",
            "activation_status": "older_deactivated",
            "username": "user3",
            "ccri": "dunno",
            "email": "user3@mail.ca",
            "member_since": "2020-05-01 15:47:52 -0400",
        },
        # user4: a user with multiple deactivated entries, the last one should be kept
        {
            "rapi": "therapi",
            "groupname": "thegroup",
            "name": "User Fantastic Four",
            "position": "Étudiant 1er cycle",
            "institution": "random uni",
            "department": "patate",
            "sponsor": "John Doe",
            "permission": "Member",
            "activation_status": "older_deactivated",
            "username": "user4",
            "ccri": "dunno",
            "email": "user4@mail.ca",
            "member_since": "2017-04-27 17:12:50 -0400",
        },
        {
            "rapi": "therapi",
            "groupname": "thegroup",
            "name": "User Fantastic Four",
            "position": "Étudiant à la maîtrise",
            "institution": "random uni",
            "department": "patate",
            "sponsor": "John Doe",
            "permission": "Member",
            "activation_status": "older_deactivated",
            "username": "user4",
            "ccri": "dunno",
            "email": "user4@mail.ca",
            "member_since": "2017-04-27 17:12:50 -0400",
        },
        {
            "rapi": "therapi",
            "groupname": "thegroup",
            "name": "User Fantastic Four",
            "position": "Étudiant au doctorat",
            "institution": "random uni",
            "department": "patate",
            "sponsor": "John Doe",
            "permission": "Member",
            "activation_status": "older_deactivated",
            "username": "user4",
            "ccri": "dunno",
            "email": "user4@mail.ca",
            "member_since": "2017-04-27 17:12:50 -0400",
        },
    ]

    # Expected output
    expected_output = [
        {
            "rapi": "therapi",
            "groupname": "thegroup",
            "name": "User One",
            "position": "Chercheur",
            "institution": "random uni",
            "department": "patate",
            "sponsor": "John Doe",
            "permission": "Member",
            "activation_status": "activated",
            "username": "user1",
            "ccri": "dunno",
            "email": "user1@mail.ca",
            "member_since": "2020-05-01 15:47:52 -0400",
        },
        {
            "rapi": "therapi",
            "groupname": "thegroup",
            "name": "User Two",
            "position": "Chercheur",
            "institution": "random uni",
            "department": "patate",
            "sponsor": "John Doe",
            "permission": "Member",
            "activation_status": "activated",
            "username": "user2",
            "ccri": "dunno",
            "email": "user2@mail.ca",
            "member_since": "2020-05-01 15:47:52 -0400",
        },
        {
            "rapi": "therapi",
            "groupname": "thegroup",
            "name": "User The Third",
            "position": "Chercheur",
            "institution": "random uni",
            "department": "patate",
            "sponsor": "John Doe",
            "permission": "Member",
            "activation_status": "older_deactivated",
            "username": "user3",
            "ccri": "dunno",
            "email": "user3@mail.ca",
            "member_since": "2020-05-01 15:47:52 -0400",
        },
        {
            "rapi": "therapi",
            "groupname": "thegroup",
            "name": "User Fantastic Four",
            "position": "Étudiant au doctorat",
            "institution": "random uni",
            "department": "patate",
            "sponsor": "John Doe",
            "permission": "Member",
            "activation_status": "older_deactivated",
            "username": "user4",
            "ccri": "dunno",
            "email": "user4@mail.ca",
            "member_since": "2017-04-27 17:12:50 -0400",
        },
    ]

    # Call the function
    filtered_members = filter_duplicate_drac_members(LD_drac_members)

    # Assert the result
    assert filtered_members == expected_output
