"""empty message

Revision ID: 0d7c2fffa4bb
Revises: e48cef9efb1e
Create Date: 2026-06-04 13:33:23.905931+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d7c2fffa4bb'
down_revision: Union[str, Sequence[str], None] = 'e48cef9efb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slurm_jobs', 'requested_cpu',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'requested_mem',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'requested_node',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'requested_billing',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'requested_gres_gpu',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'allocated_cpu',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'allocated_mem',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'allocated_node',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'allocated_billing',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'allocated_gres_gpu',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slurm_jobs', 'allocated_gres_gpu',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'allocated_billing',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'allocated_node',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'allocated_mem',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'allocated_cpu',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'requested_gres_gpu',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'requested_billing',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'requested_node',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'requested_mem',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('slurm_jobs', 'requested_cpu',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
