"""empty message

Revision ID: 0f4a1b834088
Revises: b9acf1094135
Create Date: 2026-08-17 21:10:35.664298+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f4a1b834088"
down_revision: Union[str, Sequence[str], None] = "b9acf1094135"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_slurm_jobs_submit_gpu",
        "slurm_jobs",
        ["submit_time"],
        unique=False,
        postgresql_where=sa.text(
            "allocated_gres_gpu > 0 AND harmonized_gpu_type IS NOT NULL"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_slurm_jobs_submit_gpu",
        table_name="slurm_jobs",
        postgresql_where=sa.text(
            "allocated_gres_gpu > 0 AND harmonized_gpu_type IS NOT NULL"
        ),
    )
    # ### end Alembic commands ###
