"""Indexes for the /dash RGU window filter (see SlurmJobDB.__table_args__).

Revision ID: 197a04c604df
Revises: 786e5c05fb89
Create Date: 2026-08-05 13:20:20.586927+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "197a04c604df"
down_revision: Union[str, Sequence[str], None] = "786e5c05fb89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_slurm_jobs_end_time", "slurm_jobs", ["end_time"], unique=False)
    op.create_index(
        "ix_slurm_jobs_start_covering",
        "slurm_jobs",
        ["start_time"],
        unique=False,
        postgresql_include=[
            "id",
            "end_time",
            "elapsed_time",
            "allocated_gpu_type",
            "harmonized_gpu_type",
            "allocated_gres_gpu",
            "cluster_id",
            "cluster_user",
            "sarc_user_id",
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_slurm_jobs_start_covering",
        table_name="slurm_jobs",
        postgresql_include=[
            "id",
            "end_time",
            "elapsed_time",
            "allocated_gpu_type",
            "harmonized_gpu_type",
            "allocated_gres_gpu",
            "cluster_id",
            "cluster_user",
            "sarc_user_id",
        ],
    )
    op.drop_index("ix_slurm_jobs_end_time", table_name="slurm_jobs")
    # ### end Alembic commands ###
