"""empty message

Revision ID: 5d6e3593ea8b
Revises: 96c26f4d2fc8
Create Date: 2026-07-23 17:06:42.539520+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d6e3593ea8b"
down_revision: Union[str, Sequence[str], None] = "96c26f4d2fc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_cluster_name", "clusters", ["name"], unique=True, postgresql_include=["id"]
    )
    op.drop_constraint(
        op.f("slurm_jobs_cluster_id_submit_time_job_id_key"),
        "slurm_jobs",
        type_="unique",
    )
    op.create_index(
        "ix_job_unique",
        "slurm_jobs",
        ["cluster_id", "submit_time", "job_id"],
        unique=True,
        postgresql_include=["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_unique", table_name="slurm_jobs", postgresql_include=["id"])
    op.create_unique_constraint(
        op.f("slurm_jobs_cluster_id_submit_time_job_id_key"),
        "slurm_jobs",
        ["cluster_id", "submit_time", "job_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index("ix_cluster_name", table_name="clusters", postgresql_include=["id"])
    # ### end Alembic commands ###
