"""empty message

Revision ID: 6037cb1af327
Revises: b34d8605ec6d
Create Date: 2026-08-21 17:02:22.451671+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6037cb1af327"
down_revision: Union[str, Sequence[str], None] = "b34d8605ec6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_slurm_jobs_end_gpu_stats",
        "slurm_jobs",
        [sa.literal_column("slurm_job_end(start_time, elapsed_time)")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_slurm_jobs_end_gpu_stats", table_name="slurm_jobs")
    # ### end Alembic commands ###
