"""empty message

Revision ID: 8b64449c3eda
Revises: ca3d9ce31858
Create Date: 2026-06-23 16:23:51.509307+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b64449c3eda"
down_revision: Union[str, Sequence[str], None] = "ca3d9ce31858"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_jobstatisticdb_name"), "jobstatisticdb", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobstatisticdb_name"), table_name="jobstatisticdb")
    # ### end Alembic commands ###
