"""empty message

Revision ID: 973eac0992fa
Revises: b9acf1094135
Create Date: 2026-08-13 13:54:15.860566+00:00

"""

from typing import Sequence, Union

from alembic_utils.pg_function import PGFunction

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "973eac0992fa"
down_revision: Union[str, Sequence[str], None] = "b9acf1094135"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_slurm_job_run = PGFunction(
        schema="public",
        signature="slurm_job_run(job_start timestamptz, job_elapsed double precision)",
        definition="returns tstzrange\nlanguage sql\nimmutable\nstrict\nparallel safe\nas $$ select tstzrange(job_start, job_start + make_interval(secs => job_elapsed), '[)') $$",
    )
    op.replace_entity(public_slurm_job_run)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_slurm_job_run = PGFunction(
        schema="public",
        signature="slurm_job_run(job_start timestamp with time zone, job_elapsed double precision)",
        definition="returns tstzrange\n LANGUAGE sql\n IMMUTABLE PARALLEL SAFE STRICT\nAS $function$ select tstzrange(job_start, job_start + make_interval(secs => job_elapsed)) $function$",
    )
    op.replace_entity(public_slurm_job_run)
    # ### end Alembic commands ###
