"""empty message

Revision ID: b34d8605ec6d
Revises: 4df0156c09ee
Create Date: 2026-08-18 17:16:06.310195+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b34d8605ec6d"
down_revision: Union[str, Sequence[str], None] = "4df0156c09ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_slurm_job_end = PGFunction(
        schema="public",
        signature="slurm_job_end(job_start timestamptz, job_elapsed double precision)",
        definition="returns timestamptz\nlanguage sql\nimmutable\nstrict\nparallel safe\nas $$ select case when job_elapsed > 0 then job_start + make_interval(secs => job_elapsed) end $$",
    )
    op.create_entity(public_slurm_job_end)

    op.drop_index(
        op.f("ix_slurm_jobs_submit_gpu_type"),
        table_name="slurm_jobs",
        postgresql_include=[
            "id",
            "harmonized_gpu_type",
            "allocated_gres_gpu",
            "elapsed_time",
            "cluster_id",
            "cluster_user",
            "sarc_user_id",
        ],
    )
    op.create_index(
        "ix_slurm_jobs_end_gpu",
        "slurm_jobs",
        [sa.literal_column("slurm_job_end(start_time, elapsed_time)")],
        unique=False,
        postgresql_include=[
            "start_time",
            "elapsed_time",
            "id",
            "harmonized_gpu_type",
            "allocated_gres_gpu",
            "cluster_id",
            "cluster_user",
            "sarc_user_id",
            "job_state",
        ],
        postgresql_where=sa.text(
            "allocated_gres_gpu > 0 AND harmonized_gpu_type IS NOT NULL"
        ),
    )
    op.create_index(
        "ix_slurm_jobs_submit",
        "slurm_jobs",
        ["submit_time"],
        unique=False,
        postgresql_include=[
            "id",
            "harmonized_gpu_type",
            "allocated_gpu_type",
            "allocated_gres_gpu",
            "elapsed_time",
            "cluster_id",
            "cluster_user",
            "sarc_user_id",
            "start_time",
            "time_limit",
            "job_state",
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_slurm_jobs_submit",
        table_name="slurm_jobs",
        postgresql_include=[
            "id",
            "harmonized_gpu_type",
            "allocated_gpu_type",
            "allocated_gres_gpu",
            "elapsed_time",
            "cluster_id",
            "cluster_user",
            "sarc_user_id",
            "start_time",
            "time_limit",
            "job_state",
        ],
    )
    op.drop_index(
        "ix_slurm_jobs_end_gpu",
        table_name="slurm_jobs",
        postgresql_include=[
            "start_time",
            "elapsed_time",
            "id",
            "harmonized_gpu_type",
            "allocated_gres_gpu",
            "cluster_id",
            "cluster_user",
            "sarc_user_id",
            "job_state",
        ],
        postgresql_where=sa.text(
            "allocated_gres_gpu > 0 AND harmonized_gpu_type IS NOT NULL"
        ),
    )
    op.create_index(
        op.f("ix_slurm_jobs_submit_gpu_type"),
        "slurm_jobs",
        ["submit_time", "allocated_gpu_type"],
        unique=False,
        postgresql_include=[
            "id",
            "harmonized_gpu_type",
            "allocated_gres_gpu",
            "elapsed_time",
            "cluster_id",
            "cluster_user",
            "sarc_user_id",
        ],
    )
    public_slurm_job_end = PGFunction(
        schema="public",
        signature="slurm_job_end(job_start timestamptz, job_elapsed double precision)",
        definition="returns timestamptz\nlanguage sql\nimmutable\nstrict\nparallel safe\nas $$ select case when job_elapsed > 0 then job_start + make_interval(secs => job_elapsed) end $$",
    )
    op.drop_entity(public_slurm_job_end)

    # ### end Alembic commands ###
