"""empty message

Revision ID: b9acf1094135
Revises: 4df0156c09ee
Create Date: 2026-08-13 00:52:46.467728+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9acf1094135"
down_revision: Union[str, Sequence[str], None] = "4df0156c09ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_slurm_job_run = PGFunction(
        schema="public",
        signature="slurm_job_run(job_start timestamptz, job_elapsed double precision)",
        definition="returns tstzrange\nlanguage sql\nimmutable\nstrict\nparallel safe\nas $$ select tstzrange(job_start, job_start + make_interval(secs => job_elapsed), '[)') $$",
    )
    op.create_entity(public_slurm_job_run)

    op.create_index(
        "ix_slurm_jobs_run",
        "slurm_jobs",
        [sa.literal_column("slurm_job_run(start_time, elapsed_time)")],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_slurm_jobs_run", table_name="slurm_jobs", postgresql_using="gist")
    public_slurm_job_run = PGFunction(
        schema="public",
        signature="slurm_job_run(job_start timestamptz, job_elapsed double precision)",
        definition="returns tstzrange\nlanguage sql\nimmutable\nstrict\nparallel safe\nas $$ select tstzrange(job_start, job_start + make_interval(secs => job_elapsed), '[)') $$",
    )
    op.drop_entity(public_slurm_job_run)

    # ### end Alembic commands ###
