"""empty message

Revision ID: ce6300483aaf
Revises: e48cef9efb1e
Create Date: 2026-06-02 19:35:23.541424+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce6300483aaf"
down_revision: Union[str, Sequence[str], None] = "23cb46269fc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slurm_jobs",
        sa.Column(
            "harmonized_gpu_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.create_foreign_key(
        None,
        "slurm_jobs",
        "gpurgudb",
        ["harmonized_gpu_type"],
        ["name"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "slurm_jobs", type_="foreignkey")
    op.drop_column("slurm_jobs", "harmonized_gpu_type")
    # ### end Alembic commands ###
