"""empty message

Revision ID: d7fce3746ec9
Revises:
Create Date: 2026-05-29 05:23:41.728319+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_utils.pg_extension import PGExtension
from sqlalchemy.dialects import postgresql

import sarc.db.sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7fce3746ec9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_btree_gist = PGExtension(schema="public", signature="btree_gist")
    op.create_entity(public_btree_gist)  # ty:ignore[unresolved-attribute]

    op.create_table(
        "clusters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column(
            "end_time_sacct", sarc.db.sqlmodel.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "end_time_prometheus",
            sarc.db.sqlmodel.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("billing_is_gpu", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "gpurgudb",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rgu", sa.Float(), nullable=False),
        sa.Column("drac_rgu", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "healthcheckstatedb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "check_dict", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "last_result_dict", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("last_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "idx_healthcheck_name", "healthcheckstatedb", ["name"], unique=False
    )
    op.create_table(
        "parsedates",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sarc.db.sqlmodel.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "allocationdb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("resource_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("group_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "timestamp", sarc.db.sqlmodel.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("start", sa.Date(), nullable=False),
        sa.Column("end", sa.Date(), nullable=False),
        sa.Column("gpu_year", sa.Integer(), nullable=True),
        sa.Column("cpu_year", sa.Integer(), nullable=True),
        sa.Column("rgu_year", sa.Integer(), nullable=True),
        sa.Column("vcpu_year", sa.Integer(), nullable=True),
        sa.Column("vgpu_year", sa.Integer(), nullable=True),
        sa.Column("project_inodes", sa.Float(), nullable=True),
        sa.Column("cloud_volume", sa.BigInteger(), nullable=True),
        sa.Column("cloud_shared", sa.BigInteger(), nullable=True),
        sa.Column("project_size", sa.BigInteger(), nullable=True),
        sa.Column("nearline_size", sa.BigInteger(), nullable=True),
        sa.Column("dCache", sa.BigInteger(), nullable=True),
        sa.Column("object", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_allocationdb_cluster_id"), "allocationdb", ["cluster_id"], unique=False
    )
    op.create_table(
        "credentialsdb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("valid", postgresql.TSTZRANGE(), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("domain"), "="),
            (sa.column("username"), "="),
            (sa.column("valid"), "&&"),
            using="gist",
        ),
        postgresql.ExcludeConstraint(
            (sa.column("user_id"), "="),
            (sa.column("domain"), "="),
            (sa.column("valid"), "&&"),
            using="gist",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "diskusage_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp", sarc.db.sqlmodel.UTCDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cluster_time",
        "diskusage_reports",
        ["cluster_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "gpubillingdb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("since", sarc.db.sqlmodel.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "gpu_to_billing", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cluster_since_gpu_billing",
        "gpubillingdb",
        ["cluster_id", "since"],
        unique=False,
    )
    op.create_table(
        "matchingid",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plugin_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("match_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plugin_name", "match_id"),
    )
    op.create_index(
        "user_match_id_idx", "matchingid", ["user_id", "plugin_name"], unique=True
    )
    op.create_table(
        "membertypedb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("valid", postgresql.TSTZRANGE(), nullable=False),
        sa.Column(
            "member_type",
            sa.Enum(
                "MASTER_RESEARCH",
                "MASTER_PRO",
                "PHD_STUDENT",
                "POSTDOC",
                "PROFESSOR",
                "STAFF",
                "INTERN",
                name="membertype",
            ),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("user_id"), "="), (sa.column("valid"), "&&"), using="gist"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nodegpumappingdb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("since", sarc.db.sqlmodel.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "node_to_gpu", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cluster_since_node_gpu_mapping",
        "nodegpumappingdb",
        ["cluster_id", "since"],
        unique=False,
    )
    op.create_table(
        "slurm_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("account", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("array_job_id", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cluster_user", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("group", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "job_state",
            sa.Enum(
                "BOOT_FAIL",
                "CANCELLED",
                "COMPLETED",
                "CONFIGURING",
                "COMPLETING",
                "DEADLINE",
                "FAILED",
                "NODE_FAIL",
                "OUT_OF_MEMORY",
                "PENDING",
                "PREEMPTED",
                "RUNNING",
                "RESV_DEL_HOLD",
                "REQUEUE_FED",
                "REQUEUE_HOLD",
                "REQUEUED",
                "RESIZING",
                "REVOKED",
                "SIGNALING",
                "SPECIAL_EXIT",
                "STAGE_OUT",
                "STOPPED",
                "SUSPENDED",
                "TIMEOUT",
                name="slurmstate",
            ),
            nullable=False,
        ),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("signal", sa.Integer(), nullable=True),
        sa.Column("partition", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nodes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("work_dir", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("submit_line", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("constraints", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("qos", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("CLEAR_SCHEDULING", sa.Boolean(), nullable=False),
        sa.Column("STARTED_ON_SUBMIT", sa.Boolean(), nullable=False),
        sa.Column("STARTED_ON_SCHEDULE", sa.Boolean(), nullable=False),
        sa.Column("STARTED_ON_BACKFILL", sa.Boolean(), nullable=False),
        sa.Column("time_limit", sa.Integer(), nullable=True),
        sa.Column(
            "submit_time", sarc.db.sqlmodel.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "start_time", sarc.db.sqlmodel.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "end_time", sarc.db.sqlmodel.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("elapsed_time", sa.Float(), nullable=False),
        sa.Column(
            "latest_scraped_start",
            sarc.db.sqlmodel.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "latest_scraped_end",
            sarc.db.sqlmodel.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("requested_cpu", sa.Integer(), nullable=True),
        sa.Column("requested_mem", sa.Integer(), nullable=True),
        sa.Column("requested_node", sa.Integer(), nullable=True),
        sa.Column("requested_billing", sa.Integer(), nullable=True),
        sa.Column("requested_gres_gpu", sa.Integer(), nullable=True),
        sa.Column(
            "requested_gpu_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("allocated_cpu", sa.Integer(), nullable=True),
        sa.Column("allocated_mem", sa.Integer(), nullable=True),
        sa.Column("allocated_node", sa.Integer(), nullable=True),
        sa.Column("allocated_billing", sa.Integer(), nullable=True),
        sa.Column("allocated_gres_gpu", sa.Integer(), nullable=True),
        sa.Column(
            "allocated_gpu_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("sarc_user_id", sa.Integer(), nullable=False),
        sa.CheckConstraint("start_time <= end_time"),
        sa.CheckConstraint("submit_time <= start_time"),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sarc_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cluster_id", "job_id", "submit_time"),
    )
    op.create_table(
        "user_supervisors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("valid", postgresql.TSTZRANGE(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("user_id"), "="), (sa.column("valid"), "&&"), using="gist"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "diskusage_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("group_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["report_id"], ["diskusage_reports.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diskusage_groups_report_id"),
        "diskusage_groups",
        ["report_id"],
        unique=False,
    )
    op.create_table(
        "jobstatisticdb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mean", sa.Float(), nullable=True),
        sa.Column("std", sa.Float(), nullable=True),
        sa.Column("q05", sa.Float(), nullable=True),
        sa.Column("q25", sa.Float(), nullable=True),
        sa.Column("median", sa.Float(), nullable=True),
        sa.Column("q75", sa.Float(), nullable=True),
        sa.Column("max", sa.Float(), nullable=True),
        sa.Column("unused", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["slurm_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "supervisorshelper",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("pos", sa.Integer(), nullable=False),
        sa.Column("supervisor", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["list_id"], ["user_supervisors.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["supervisor"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("list_id", "pos"),
    )
    op.create_index(
        op.f("ix_supervisorshelper_list_id"),
        "supervisorshelper",
        ["list_id"],
        unique=False,
    )
    op.create_table(
        "diskusage_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nbr_files", sa.Integer(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["diskusage_groups.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diskusage_users_group_id"),
        "diskusage_users",
        ["group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_diskusage_users_group_id"), table_name="diskusage_users")
    op.drop_table("diskusage_users")
    op.drop_index(op.f("ix_supervisorshelper_list_id"), table_name="supervisorshelper")
    op.drop_table("supervisorshelper")
    op.drop_table("jobstatisticdb")
    op.drop_index(op.f("ix_diskusage_groups_report_id"), table_name="diskusage_groups")
    op.drop_table("diskusage_groups")
    op.drop_table("user_supervisors")
    op.drop_table("slurm_jobs")
    op.drop_index("idx_cluster_since_node_gpu_mapping", table_name="nodegpumappingdb")
    op.drop_table("nodegpumappingdb")
    op.drop_table("membertypedb")
    op.drop_index("user_match_id_idx", table_name="matchingid")
    op.drop_table("matchingid")
    op.drop_index("idx_cluster_since_gpu_billing", table_name="gpubillingdb")
    op.drop_table("gpubillingdb")
    op.drop_index("idx_cluster_time", table_name="diskusage_reports")
    op.drop_table("diskusage_reports")
    op.drop_table("credentialsdb")
    op.drop_index(op.f("ix_allocationdb_cluster_id"), table_name="allocationdb")
    op.drop_table("allocationdb")
    op.drop_table("users")
    op.drop_table("parsedates")
    op.drop_index("idx_healthcheck_name", table_name="healthcheckstatedb")
    op.drop_table("healthcheckstatedb")
    op.drop_table("gpurgudb")
    op.drop_table("clusters")
    public_btree_gist = PGExtension(schema="public", signature="btree_gist")
    op.drop_entity(public_btree_gist)  # ty:ignore[unresolved-attribute]

    # ### end Alembic commands ###
