"""empty message

Revision ID: ddd9a5450dc8
Revises: ff2a5e9c29b7
Create Date: 2026-10-08 19:30:18.006731+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddd9a5450dc8"
down_revision: Union[str, Sequence[str], None] = "ff2a5e9c29b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_jobstatistics_fetchdate_jobstatistic_id"),
        "jobstatistics_fetchdate",
        ["jobstatistic_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_jobstatistics_fetchdate_jobstatistic_id"),
        table_name="jobstatistics_fetchdate",
    )
    # ### end Alembic commands ###
