"""empty message

Revision ID: ff1795ca47a3
Revises: a24d2967a725
Create Date: 2026-06-18 18:39:29.406030+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff1795ca47a3"
down_revision: Union[str, Sequence[str], None] = "a24d2967a725"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_credentialsdb_user_id"), "credentialsdb", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_diskusage_reports_cluster_id"),
        "diskusage_reports",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gpubillingdb_cluster_id"), "gpubillingdb", ["cluster_id"], unique=False
    )
    op.create_index(
        op.f("ix_jobstatisticdb_job_id"), "jobstatisticdb", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_matchingid_user_id"), "matchingid", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_membertypedb_user_id"), "membertypedb", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_nodegpumappingdb_cluster_id"),
        "nodegpumappingdb",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        "ix_slurm_jobs_cluster_submit_time",
        "slurm_jobs",
        ["cluster_id", "submit_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_supervisors_user_id"),
        "user_supervisors",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_supervisors_user_id"), table_name="user_supervisors")
    op.drop_index("ix_slurm_jobs_cluster_submit_time", table_name="slurm_jobs")
    op.drop_index(op.f("ix_nodegpumappingdb_cluster_id"), table_name="nodegpumappingdb")
    op.drop_index(op.f("ix_membertypedb_user_id"), table_name="membertypedb")
    op.drop_index(op.f("ix_matchingid_user_id"), table_name="matchingid")
    op.drop_index(op.f("ix_jobstatisticdb_job_id"), table_name="jobstatisticdb")
    op.drop_index(op.f("ix_gpubillingdb_cluster_id"), table_name="gpubillingdb")
    op.drop_index(
        op.f("ix_diskusage_reports_cluster_id"), table_name="diskusage_reports"
    )
    op.drop_index(op.f("ix_credentialsdb_user_id"), table_name="credentialsdb")
    # ### end Alembic commands ###
