---
name: build_the_docs_test

on:
  pull_request:
    branches:
      - master

jobs:
  btd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: buildthedocs/btd@v0
        with:
          token: ${{ github.token }}
          skip-deploy: true

      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/_build/html
